// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYUcrwtfQyRlQeblxIwle2VYBxcvbRqo',
    appId: '1:1055081842500:web:ce3106d17038dca1153911',
    messagingSenderId: '1055081842500',
    projectId: 'chat--app-b3ef8',
    authDomain: 'chat--app-b3ef8.firebaseapp.com',
    storageBucket: 'chat--app-b3ef8.appspot.com',
    measurementId: 'G-H7WXZL5Q8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqikcb9dOdyfW9wOr7Afv4r0FS8_oCMNM',
    appId: '1:1055081842500:android:7caf339f55f88401153911',
    messagingSenderId: '1055081842500',
    projectId: 'chat--app-b3ef8',
    storageBucket: 'chat--app-b3ef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO_XQvNHx-HGdHmekcBSTZlo0GdxRcHY4',
    appId: '1:1055081842500:ios:99d79b55ee6b4816153911',
    messagingSenderId: '1055081842500',
    projectId: 'chat--app-b3ef8',
    storageBucket: 'chat--app-b3ef8.appspot.com',
    iosBundleId: 'com.example.sivvenPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO_XQvNHx-HGdHmekcBSTZlo0GdxRcHY4',
    appId: '1:1055081842500:ios:3183ed8b5879fc0e153911',
    messagingSenderId: '1055081842500',
    projectId: 'chat--app-b3ef8',
    storageBucket: 'chat--app-b3ef8.appspot.com',
    iosBundleId: 'com.example.sivvenPro.RunnerTests',
  );
}
